# NUMPY Programming

In [5]:
import numpy as np

## 1-D array

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## 2-D array

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D array

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Multi dimensional array

In [16]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Array dimensionals 

In [25]:
arr = np.array([[1, 2, 3, 4], [3,5,6, 5]], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)


[[[1 2 3 4]
  [3 5 6 5]]]
number of dimensions : 3
