## Numpy Tutorials

In [1]:
import numpy as np
arr = np.array([['a','n'],['s','h'],['y','a'],['d','a']])
print(f"Shape :{arr.shape}")
print(f"Type :{type(arr)}")
print(f"Dimention :{arr.ndim}")
print(f"Size :{arr.size}")
print(f"Type :{arr.dtype}")
print(f"Item size :{arr.itemsize}")

Shape :(4, 2)
Type :<class 'numpy.ndarray'>
Dimention :2
Size :8
Type :<U1
Item size :4


In [2]:
arr2 = np.array([[1,2],[3,4],[5,6],[7,8]],dtype='f')
print(f"Array all :{arr2.all()}")

Array all :True


In [3]:
arr3 = np.array((1,2,3))
print(f"Array Tuple :{arr3}")

Array Tuple :[1 2 3]


In [4]:
arrZero = np.zeros((3,5),dtype='f')
print(f"Array Zeros :\n{arrZero}")

Array Zeros :
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
arrOnes = np.ones((3,5),dtype='f')
print(f"Array Ones :\n{arrOnes}")

Array Ones :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
print(f"Arange :\n{np.arange(0,11,5)}")

Arange :
[ 0  5 10]


In [7]:
print(f"Random :\n{np.random.random((2,5))}")

Random :
[[0.82050213 0.3686004  0.34059366 0.37728807 0.12699447]
 [0.40535968 0.17309965 0.97848749 0.78225716 0.34157704]]


In [8]:
print(f"Linespace :\n{np.linspace(0,50,100)}")

Linespace :
[ 0.          0.50505051  1.01010101  1.51515152  2.02020202  2.52525253
  3.03030303  3.53535354  4.04040404  4.54545455  5.05050505  5.55555556
  6.06060606  6.56565657  7.07070707  7.57575758  8.08080808  8.58585859
  9.09090909  9.5959596  10.1010101  10.60606061 11.11111111 11.61616162
 12.12121212 12.62626263 13.13131313 13.63636364 14.14141414 14.64646465
 15.15151515 15.65656566 16.16161616 16.66666667 17.17171717 17.67676768
 18.18181818 18.68686869 19.19191919 19.6969697  20.2020202  20.70707071
 21.21212121 21.71717172 22.22222222 22.72727273 23.23232323 23.73737374
 24.24242424 24.74747475 25.25252525 25.75757576 26.26262626 26.76767677
 27.27272727 27.77777778 28.28282828 28.78787879 29.29292929 29.7979798
 30.3030303  30.80808081 31.31313131 31.81818182 32.32323232 32.82828283
 33.33333333 33.83838384 34.34343434 34.84848485 35.35353535 35.85858586
 36.36363636 36.86868687 37.37373737 37.87878788 38.38383838 38.88888889
 39.39393939 39.8989899  40.4040404  40.

In [9]:
print(f"Diagonal eye :\n{np.eye(15)}")

Diagonal eye :
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
print(f"Random :\n{np.random.rand(5,10)}")

Random :
[[0.20712214 0.44516203 0.59053647 0.43627339 0.63218193 0.38483692
  0.0658321  0.97924285 0.44251113 0.58644651]
 [0.02617023 0.07151096 0.71400789 0.30931107 0.62910758 0.00124048
  0.29330166 0.15501022 0.94627082 0.90050711]
 [0.68737082 0.34945535 0.53064182 0.10349562 0.43060015 0.35455387
  0.97103675 0.27880057 0.86773667 0.02650187]
 [0.86799479 0.26457492 0.67120974 0.8926718  0.68045137 0.40155526
  0.1826063  0.8053818  0.5436181  0.35508312]
 [0.49777203 0.21751616 0.18890793 0.95680919 0.93414185 0.73932669
  0.24195922 0.80304252 0.52862725 0.73233475]]


In [11]:
print(f"Random Integer :\n{np.random.randint(1,100)}")

Random Integer :
79


In [12]:
print(f"Reshape :\n{np.arange(40).reshape(4,10)}")

Reshape :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [13]:
print(f"Max value : {np.arange(100).max()}")

Max value : 99


In [14]:
print(f"Max argument ( return index ) :{np.arange(100).argmax()}")

Max argument ( return index ) :99


In [15]:
print(f"Min argument ( return index ) :{np.arange(100).argmin()}")

Min argument ( return index ) :0


# Chapter 6
## Excercies Question no 4

In [16]:
print(f"A) 1-D array called zeros having 10 elements and all the elements are set to zero. :{np.zeros(10)}")

A) 1-D array called zeros having 10 elements and all the elements are set to zero. :[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
print(f"B) A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. :{np.array(['a','e','i','o','u'])}")

B) A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. :['a' 'e' 'i' 'o' 'u']


In [18]:
print(f"C) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. :\n{np.ones((2,5),dtype='i')}")

C) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. :
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
print(f"D) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data :\n{np.array([[2.7,-2,-19],[0, 3.4, 99.9],[10.6, 0, 13]])}")

D) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data :
[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


In [20]:
print(f"E) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float. :\n{np.arange(4,62,4).reshape(3,5)}")

E) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float. :
[[ 4  8 12 16 20]
 [24 28 32 36 40]
 [44 48 52 56 60]]


## Quesiton 5

In [21]:
# 1
print(np.arange(4,62,4).reshape(3,5).dtype)
print(np.array([[2.7,-2,-19],[0, 3.4, 99.9],[10.6, 0, 13]]).dtype)
print()

# 2
print(np.arange(10).reshape(2,5))
print()

# 3
print(np.array(['a','e','i','o','u'])[1:3])
print()

# 4
arr = np.arange(4,62,4).reshape(3,5)
print(arr)
print(arr[1:3])
print()

# 5
print(arr[:,1:3])

# 6
print(arr[:,0][1:3])
print()
# 7
print(np.array(['a','e','i','o','u'])[::-1])

int64
float64

[[0 1 2 3 4]
 [5 6 7 8 9]]

['e' 'i']

[[ 4  8 12 16 20]
 [24 28 32 36 40]
 [44 48 52 56 60]]
[[24 28 32 36 40]
 [44 48 52 56 60]]

[[ 8 12]
 [28 32]
 [48 52]]
[24 44]

['u' 'o' 'i' 'e' 'a']


## Question 6

In [22]:
# a
print(np.ones(10)/3)

# b
arr1 = np.arange(0,100,5)
arr2 = np.arange(0,200,10)
print(arr1)
print(arr2)
print("\nOutput ",arr1 + arr2)
print(np.add(arr1,arr2))
print()

# c
print(arr1-arr2)
print(np.subtract(arr1,arr2))
print()

# d
print(arr1*arr2)
print(np.multiply(arr1,arr2))
print()

# e
arr12 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr22 = np.array([[11,22,33,44],[55,66,77,88],[99,110,111,112],[113,114,115,116]])
print(f"E {arr12} \n\n {arr22}\n\n")
print(np.matmul(arr12,arr22))
print()

# f
print(arr12/arr22)
print(np.divide(arr12,arr22))
print()

# g
print(arr12**3)
print(np.divide(arr12**3,2))
print()

# h
print(np.round(np.divide(arr12**3,2),decimals=2))

[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333
 0.33333333 0.33333333 0.33333333 0.33333333]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]

Output  [  0  15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255
 270 285]
[  0  15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255
 270 285]

[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85
 -90 -95]
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85
 -90 -95]

[    0    50   200   450   800  1250  1800  2450  3200  4050  5000  6050
  7200  8450  9800 11250 12800 14450 16200 18050]
[    0    50   200   450   800  1250  1800  2450  3200  4050  5000  6050
  7200  8450  9800 11250 12800 14450 16200 18050]

E [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

 [[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 111 112]
 [113 114 115 116]]


[[ 870 

## Question 7

In [23]:
# a
print(np.ones(25).reshape(5,5).transpose())
print(np.arange(25).reshape(5,5).transpose())

# c
print(arr12.sort())


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
None


In [24]:
arr = np.arange(40).reshape(4,10)
print(arr)
print(arr.transpose())

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]
 [ 4 14 24 34]
 [ 5 15 25 35]
 [ 6 16 26 36]
 [ 7 17 27 37]
 [ 8 18 28 38]
 [ 9 19 29 39]]
