## Imports

In [1]:
import numpy as np

## Practical 1

In [2]:
data1 = [[6,7,5],[8,0,1]]
arr1 = np.array(data1)
print(f"Array :{arr1}")
print(f"Dtype :{arr1.dtype}")
print(f"Shape :{arr1.shape}")
print(f"N dimention :{arr1.ndim}")

Array :[[6 7 5]
 [8 0 1]]
Dtype :int64
Shape :(2, 3)
N dimention :2


In [3]:
print(f"Zeros :\n{np.zeros((2,4))}\n")
print(f"Ones :\n{np.ones((2,3))}\n")
print(f"Eye :\n{np.eye(3)}\n")
print(f"Arange :\n{np.arange(0,10,2)}\n")
print(f"Mulitply :\n{arr1[0]*arr1[1]}\n")
print(f"Power :\n{arr1[0]**2}\n")
print(f"Comparison :\n{arr1[0]>arr1[1]}\n")

Zeros :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones :
[[1. 1. 1.]
 [1. 1. 1.]]

Eye :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange :
[0 2 4 6 8]

Mulitply :
[48  0  5]

Power :
[36 49 25]

Comparison :
[False  True  True]



In [4]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Array slicing :\n{arr2[1:-2]}\n")
arrSlice = arr2[5:8]
arrSlice[1]=123
print(f"Array update using slicing :\n{arr2}\n")

Array slicing :
[2 3 4 5 6 7 8]

Array update using slicing :
[  1   2   3   4   5   6 123   8   9  10]



In [5]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[1,1:3])

[5 6]


## Jay Patel

In [6]:
print("1. Array Creation")
a  = np.array([1,2,3,4,5])
print("Array from list:",a)

b = np.array([[1,2,3],[4,5,6]])
print("2D array :",b)
print("Array of zeros\n",np.zeros((5,3)))
print("Array of ones:\n",np.ones((2,4)))
print("Empty array:\n",np.empty((2,3)))
print("Array of a range\n",np.arange(0,20,2))
print("Array with evenly spaces values \n",np.linspace(0,1,5))
print("Array with random values :\n",np.random.random((2,4)))

1. Array Creation
Array from list: [1 2 3 4 5]
2D array : [[1 2 3]
 [4 5 6]]
Array of zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of a range
 [ 0  2  4  6  8 10 12 14 16 18]
Array with evenly spaces values 
 [0.   0.25 0.5  0.75 1.  ]
Array with random values :
 [[0.55206884 0.06713099 0.99990172 0.36044326]
 [0.6895272  0.13450492 0.82563501 0.44126333]]


In [7]:
print("\n\n2. Array indexing and slicing \n")
c = np.array([10,20,30,40,50,60,70,80,90,100])
print("Original array \n",c)
print(c[1:-3])
d = np.array([[10,20,30,60],[40,50,60,80],[70,80,90,50],[100,110,120,450]])
print("2D array",d)
print("\n",d[0,:])



2. Array indexing and slicing 

Original array 
 [ 10  20  30  40  50  60  70  80  90 100]
[20 30 40 50 60 70]
2D array [[ 10  20  30  60]
 [ 40  50  60  80]
 [ 70  80  90  50]
 [100 110 120 450]]

 [10 20 30 60]


In [8]:
print("Reshaping")
e = np.arange(12)
reshaped = e.reshape(3,4)
print(reshaped)

## mathematical operations
f = np.array([1,2,3])
g = np.array([4,5,6])

print("Addition",f+g)
print("Subtract",f-g)
print("Exponential",np.exp(f))
print("Square root",np.sqrt(f))
print("Sum of array",np.sum(f))
print("Sum along axis 0",np.sum(f,axis=0))
print("Mean of array",np.mean(f))
print("Standard deviation of array",np.std(f))

print("Matrix multipliction",np.dot(f,g))
print("Determinant",np.linalg.det(d))
print("Inverstion",np.linalg.inv(d))

Reshaping
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Addition [5 7 9]
Subtract [-3 -3 -3]
Exponential [ 2.71828183  7.3890561  20.08553692]
Square root [1.         1.41421356 1.73205081]
Sum of array 6
Sum along axis 0 6
Mean of array 2.0
Standard deviation of array 0.816496580927726
Matrix multipliction 32
Determinant 1.2889689315898067e-10
Inverstion [[-1.00079992e+15  1.88522775e+15 -7.68055750e+14 -1.16372083e+14]
 [ 2.00159983e+15 -3.77045550e+15  1.53611150e+15  2.32744167e+14]
 [-1.00079992e+15  1.88522775e+15 -7.68055750e+14 -1.16372083e+14]
 [-2.22222222e-02  4.41860465e-02 -2.17054264e-02 -2.58397933e-04]]
